### ISSUE TITLE
运行存在问题

### ISSUE THREAD

**Issue by dosopeng** [Peakmain/AsmActualCombat#4]
build没问题 run的时候 org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':app:yingyongbaoDebugRuntimeClasspath'. 是不是gradle版本差距太大的问题？

**Comment by Peakmain** [comment]
请问你的gradle版本是多少

**Comment by Peakmain** [comment]
你可以看下最新文档接入方式：https://github.com/Peakmain/AsmActualCombat#%E6%96%B0%E7%89%88%E6%9C%AC%E6%B7%BB%E5%8A%A0%E6%96%B9%E5%BC%8F
