### ISSUE TITLE
build报错麻烦看下，谢谢

### ISSUE THREAD

**Issue by ZJLeBron** [Peakmain/AsmActualCombat#6]

**Comment by ZJLeBron** [comment]
Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :architecture project caused this error: F:\zhiyuan\exampleappand\Example\architecture\libs\netmobsecLib_4.4.7.4_202209211104.aar, F:\zhiyuan\exampleappand\Example\architecture\libs\xlog_release.aar

**Comment by Peakmain** [comment]
你可以看下这篇文章https://blog.csdn.net/yuanzhihui123/article/details/123653733
